[workspace]
resolver = "3"

members = [
    "rig-extra",
    "examples/bigmodel_provider_demo",
    "examples/rmcp_demo",
    "examples/rand_agent_demo",
    "examples/retry_demo",
    "examples/tools_demo"
]

