[package]
name = "rand_agent_demo"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
rig-extra = { path = "../../rig-extra" }
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
config = "0.15.11"