[package]
name = "retry_demo"
version = "0.1.0"
edition = "2024"

[dependencies]
rig-extra = { path = "../../rig-extra" }
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
anyhow = "1.0.98"